[AutoRun]
enabled=false
program=

[BitTorrent]
Session\AddTorrentStopped=false
Session\DefaultSavePath=/Media/Downloads/complete/
Session\Port=22379
Session\QueueingSystemEnabled=true
Session\SSL\Port=3479
Session\ShareLimitAction=Stop
Session\TempPath=/Media/Downloads/incomplete/
Session\TorrentContentRemoveOption=Delete

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
Downloads\SavePath=/downloads/
Downloads\TempPath=/Media/Downloads/incomplete/
WebUI\Address=*
WebUI\AuthSubnetWhitelist=192.168.1.0/24, 127.0.0.0/8
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\CSRFProtection=true
WebUI\HostHeaderValidation=true
WebUI\Password_PBKDF2="@ByteArray(69+jcQQq16Ld26n5lwrGSw==:+Vo0aRrJLKlt2UEJmzdMX7b9+n1wgGPWL+dVYe8IuWgBBnYs4MV9VsUMZVJ1BqeIuHOo6FLpOVj1/gljrBQjAA==)"
WebUI\Port=8888
WebUI\ServerDomains=*
WebUI\SessionTimeout=3600
WebUI\UseUPnP=true
WebUI\Username=admin
